### ISSUE TITLE
Failed to test k8s-block-volume.bats for qemu-runtime-rs for s390x

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/kata-containers#10373]
# Description of problem

Since #7165 was merged, two k8s tests for `qemu-runtime-rs` have started failing with

- run-k8s-tests-on-aks / run-k8s-tests (ubuntu, qemu-runtime-rs, small)
- run-k8s-tests-on-zvsi / run-k8s-tests (overlayfs, qemu-runtime-rs, k3s)

```
failed to create containerd task: failed to create shim task: 
Others("failed to handle message create container\n\nCaused by:\n    
0: do handle device\n    1: failed to create device\n    2: failed to create device\n    
3: unsupported driver type virtio-scsi"): unknown
```

As mentioned #10066, `qemu-runtime-rs` lacks implementation for `virtio-scsi` at the time of writing. Therefore, we should skip the test until the implementation is in place. 

FYI: @sprt @wainersm @pmores

**Comment by stevenhorsman** [comment]
@BbolroC - has this been resolved now?

**Comment by BbolroC** [comment]
> [@BbolroC](https://github.com/BbolroC) - has this been resolved now?

Nope, it hasn't. It was put in my backlog since https://github.com/kata-containers/kata-containers/pull/12105#issuecomment-3551916090. Thanks!

**Comment by BbolroC** [comment]
I'm re-opening this because the test isn't resolved for s390x. (see https://github.com/kata-containers/kata-containers/pull/12105/changes/2090ada630f7f763b2d1daa19819d537dd36b117) I will rename the title. Thanks.
