### ISSUE TITLE
Failed to start container with GPU passthrough

### ISSUE THREAD

**Issue by ChuckGithub** [kata-containers/kata-containers#10891]
The command `ctr --debug run --rm --runtime "io.containerd.kata.v2" --device /dev/vfio/324 -t ubuntu:22.04 test bash` encounters the following error:
```
WARN[0000] DEPRECATION: The `configs` property of `[plugins."io.containerd.grpc.v1.cri".registry]` is deprecated since containerd v1.5 and will be removed in containerd v2.0. Use `config_path` instead. 
DEBU[0000] remote introspection plugin filters           filters="[type==io.containerd.snapshotter.v1, id==overlayfs]"
ctr: failed to create shim task: CreateContainerRequest timed out: context deadline exceeded
```
The containerd logs contain the message "reading guest console" with additional details:
```
Feb 17 13:44:29 test containerd[140205]: time="2025-02-17T13:44:29.659236575+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=140809 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"error injecting devices: \\\"unresolvable CDI devices nvidia.com/gpu=0\\\"\",\"level\":\"INFO\",\"ts\":\"2025-02-17T05:44:29.654738876Z\",\"subsystem\":\"rpc\",\"name\":\"kata-agent\",\"pid\":\"100\",\"version\":\"0.1.0\",\"source\":\"agent\"}"
Feb 17 13:44:30 test containerd[140205]: time="2025-02-17T13:44:30.659327909+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=140809 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="error injecting devices: \"unresolvable CDI devices nvidia.com/gpu=0\""
Feb 17 13:44:30 test containerd[140205]: time="2025-02-17T13:44:30.659385190+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=140809 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"error injecting devices: \\\"unresolvable CDI devices nvidia.com/gpu=0\\\"\",\"level\":\"INFO\",\"ts\":\"2025-02-17T05:44:30.655131337Z\",\"source\":\"agent\",\"name\":\"kata-agent\",\"version\":\"0.1.0\",\"subsystem\":\"rpc\",\"pid\":\"100\"}"
Feb 17 13:44:31 test containerd[140205]: time="2025-02-17T13:44:31.660506338+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=140809 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="error injecting devices: \"unresolvable CDI devices nvidia.com/gpu=0\""
Feb 17 13:44:31 test containerd[140205]: time="2025-02-17T13:44:31.660553983+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=140809 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"error injecting devices: \\\"unresolvable CDI devices nvidia.com/gpu=0\\\"\",\"level\":\"INFO\",\"ts\":\"2025-02-17T05:44:31.656329669Z\",\"name\":\"kata-agent\",\"subsystem\":\"rpc\",\"pid\":\"100\",\"version\":\"0.1.0\",\"source\":\"agent\"}"
Feb 17 13:44:32 test containerd[140205]: time="2025-02-17T13:44:32.661601613+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=140809 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="error injecting devices: \"unresolvable CDI devices nvidia.com/gpu=0\""
Feb 17 13:44:32 test containerd[140205]: time="2025-02-17T13:44:32.661643533+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/test/console.sock name=containerd-shim-v2 pid=140809 sandbox=test source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"error injecting devices: \\\"unresolvable CDI devices nvidia.com/gpu=0\\\"\",\"level\":\"INFO\",\"ts\":\"2025-02-17T05:44:32.657443938Z\",\"version\":\"0.1.0\",\"name\":\"kata-agent\",\"source\":\"agent\",\"pid\":\"100\",\"subsystem\":\"rpc\"}"
```
bus-id `0000:da:00.0` IOMMU group is 324 
```
lspci -k -s 0000:da:00.0
da:00.0 3D controller: NVIDIA Corporation Device 2324 (rev a1)
        Subsystem: NVIDIA Corporation Device 17a8
        Kernel driver in use: vfio-pci
        Kernel modules: nouveau, nvidia_drm, nvidia
```
Hi @zvonkok , Can you give me some suggestions? Thank you.

**Comment by zvonkok** [comment]
Increase the `create_container_timeout=180`, depending on the GPU it takes some time to hot-plug and initialize the GPU.

**Comment by zvonkok** [comment]
The error message is also misleading, this is fixed in the next release.

**Comment by ChuckGithub** [comment]
> Increase the `create_container_timeout=180`, depending on the GPU it takes some time to hot-plug and initialize the GPU.

@zvonkok Thanks for your reply, I have adjusted the `create_container_timeout=180` and `kernel_params = "agent.hotplug_timeout=180"` parameter, but I am still encountering CDI errors. Is it possible to disable the CDI,  or could this be related to a specific GPU model?
```
[root@test kata-containers]# kata-runtime --version
kata-runtime  : 3.13.0
   commit   : 2777b13db748f9ba785c7d2be4fcb6ac9c9af265
   OCI specs: 1.1.0+dev

[root@test kata-containers]# containerd-shim-kata-v2 --version
Kata Containers containerd shim (Golang): id: "io.containerd.kata.v2", version: 3.13.0, commit: 2777b13db748f9ba785c7d2be4fcb6ac9c9af265

[root@test kata-containers]# containerd --version
containerd github.com/containerd/containerd v1.7.15 926c9586fe4a6236699318391cd44976a98e31f1

[root@test kata-containers]# ctr --debug run --rm --runtime "io.containerd.kata.v2" --device /dev/vfio/324 -t ubuntu:22.04 test bash
WARN[0000] DEPRECATION: The `configs` property of `[plugins."io.containerd.grpc.v1.cri".registry]` is deprecated since containerd v1.5 and will be removed in containerd v2.0. Use `config_path` instead. 
DEBU[0000] remote introspection plugin filters           filters="[type==io.containerd.snapshotter.v1, id==overlayfs]"
ctr: failed to create shim task: failed to inject devices after CDI timeout of 100 seconds

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>: unknown
```

**Comment by ChuckGithub** [comment]
> Which rootfs are you using? CDI is mandatory.

Kernel 5.15.23 with Ubuntu as the rootfs, installed GPU drivers and nvidia-container-toolkit.

**Comment by ChuckGithub** [comment]
Hi @zvonkok, With version 3.10.0 of the kata-agent (which does not include CDI support), I was able to successfully start containers and run the nvidia-smi command inside the qemu VM. 

Now, with version 3.14.0, I am trying to add CDI support using the k8s device plugin in the Allocate function, but I have not been successful after testing several scenarios, kata-agent .  Could you provide me with a simple example? Thank you very much.

device plugin code:
```
func (m *VfioDevicePlugin) Allocate(ctx context.Context, reqs *api.AllocateRequest) (*api.AllocateResponse, error) {
...
			var cdiDevices []*api.CDIDevice
			annotations := make(map[string]string, 1)
			index := 0
			for _, id := range req.DevicesIDs {
				annoKey := fmt.Sprintf("%s/vfio%s", cdiapi.AnnotationPrefix, id)
				device := cdiparser.QualifiedName("nvidia.com", "gpu", strconv.Itoa(index))
				annotations[annoKey] = device
				cdiDevices = append(cdiDevices, &api.CDIDevice{Name: fmt.Sprintf("nvidia.com/vfio=%s", id)})
				index++
			}
			klog.Infof("Allocated nvidia device CDI annotation is %s", annotations)

			response := api.ContainerAllocateResponse{
				Annotations: annotations,
				CDIDevices:  cdiDevices,
			}
```

kata-agent log:
```
time="2025-02-20T20:19:05.740958781+08:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/32ff1c8c4a506795f359e30b4b9e480471d7ad3f81e43d436bd6711e557f8d55/console.sock name=containerd-shim-v2 pid=1930940 sandbox=32ff1c8c4a506795f359e30b4b9e480471d7ad3f81e43d436bd6711e557f8d55 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"no CDI annotations, no devices to inject\",\"level\":\"INFO\",\"ts\":\"2025-02-20T12:19:05.723765257Z\",\"subsystem\":\"rpc\",\"source\":\"agent\",\"name\":\"kata-agent\",\"version\":\"0.1.0\",\"pid\":\"286\"}"
```

**Comment by ChuckGithub** [comment]
> Becasue the 3.10 version used the hook in the VM, now we use CDI, you need to have a proper guest FS. Please use
> 
> ```
> make rootfs-nvidia-gpu-initrd-tarball
> ```
> 
> And the configuration-qemu-nvidia-gpu.toml as the config.

@zvonkok Thanks, after rebuilding the guest FS, it now works fine.
