### ISSUE TITLE
kata-container snap not up to date for all architectures

### ISSUE THREAD

**Issue by frank-heimes** [kata-containers/kata-containers#2190]
On an amd64 system I can find that the latest stable kata-container snap is 2.1.1
$ snap info kata-containers
name:    kata-containers
summary: Lightweight virtual machines that seamlessly plug into the
  containers ecosystem
publisher: Kata Containers (katacontainers✓)
store-url: https://snapcraft.io/kata-containers
contact:   https://katacontainers.io/
license:   Apache-2.0 OR BSD-2-Clause OR BSD-3-Clause-Clear OR GPL-2.0 OR LGPL-2.1 OR MIT
description: |
  Kata Containers is an open source project and community working to build a
  standard implementation of lightweight Virtual Machines (VMs) that feel and
  perform like containers, but provide the workload isolation and security
  advantages of VMs
snap-id: oTlBRwmiNP4yYPYhhAipQPZ5RPvOpuOm
channels:
  latest/stable:    2.1.1 2021-06-16 (720) 96MB classic
  latest/candidate: 2.1.0 2021-05-14 (719) 96MB classic
  latest/beta:      2.0.1 2020-12-04 (710) 88MB classic
  latest/edge:      2.0.1 2020-11-18 (710) 88MB classic

However, on s390x I get 1.8.0 as latest stable:
snap info kata-containers
name:    kata-containers
summary: Lightweight virtual machines that seamlessly plug into the
  containers ecosystem
publisher: Kata Containers (katacontainers✓)
store-url: https://snapcraft.io/kata-containers
contact:   https://katacontainers.io/
license:   Apache-2.0 OR BSD-2-Clause OR BSD-3-Clause-Clear OR GPL-2.0 OR LGPL-2.1 OR MIT
description: |
  Kata Containers is an open source project and community working to build a
  standard implementation of lightweight Virtual Machines (VMs) that feel and
  perform like containers, but provide the workload isolation and security
  advantages of VMs
snap-id: oTlBRwmiNP4yYPYhhAipQPZ5RPvOpuOm
channels:
  latest/stable:    2.1.1 2021-06-16 (720) 96MB classic
  latest/candidate: 2.1.0 2021-05-14 (719) 96MB classic
  latest/beta:      2.0.1 2020-12-04 (710) 88MB classic
  latest/edge:      2.0.1 2020-11-18 (710) 88MB classic

Looks like the build stopped working for s390x - but snaps can be usually build for s390x w/o issues (if the code allows and compiles).

Could you please check why s390x became outdated and hopefully release the latest stable versions of the snap again for s390x, too?

**Comment by fidencio** [comment]
@devimc, I'm not familiar with snap at all, but do we require hardware to build for s390x, aarch64, and ppc64le?

Considering we don't need hardware, we'd need to live with a few differences between the x86_64 / aarch64 builds and the s390x / ppc64le ones, as the agent would have to be built using glibc for the latter.  Apart from this, I think that things should simply work.

@Jakob-Naucke and @davidhay1969 already mentioned they could help to get the s390x pieces in place.

**Comment by Jakob-Naucke** [comment]
trying to build...

**Comment by jodh-intel** [comment]
Yes, something's gone awry. Here's the summary of the `latest/stable` channel from https://snapcraft.io/kata-containers:

| arch | version | published |
|-|-|-|
| amd64 | 2.1.1 | 16 June 2021 |
| arm64 | 1.11.2 | 28 July 2020 |
| ppc64el | 1.12.0 | 4 December 2020 |
| s390x | 1.8.0 | 23 July 2019 |

**Comment by devimc** [comment]
@jodh-intel @fidencio @Jakob-Naucke 

> @devimc, I'm not familiar with snap at all, but do we require hardware to build for s390x, aarch64, and ppc64le?

yes, we need HW for those architectures and volunteers to maintain them, it was a PITA to maintain them in launchpad, so I took the decision to move the x86_64 snap to github actions and let those in charge of the other architectures choose their own poison for building and releasing the snap package.

**Comment by jodh-intel** [comment]
Hi @devimc - I did some digging and it looks like this might help:

- https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos

**Comment by devimc** [comment]
@jodh-intel thanks, I guess I can try and file issues if it doesn't build on other architectures

**Comment by Jakob-Naucke** [comment]
see #2193 for fixes for s390x (and a bit of ppc64le on the way)

**Comment by Jakob-Naucke** [comment]
@devimc you can retry all the architectures with #2193 merged :)

**Comment by devimc** [comment]
@Jakob-Naucke @fidencio  @jodh-intel  I'm getting this error `apply caps: operation not permitted: unknown.` (same in launchpad),  I think we'll end up in the same place :disappointed: 

```
+ docker run --rm --runtime runc --privileged --env AGENT_BIN=kata-agent --env AGENT_INIT=yes --env FS_TYPE=ext4 --env BLOCK_SIZE=4096 --env ROOT_FREE_SPACE= --env NSDAX_BIN= --env DEBUG=1 -v /dev:/dev -v /build/kata-containers/tools/osbuilder/image-builder:/osbuilder -v /build/kata-containers/tools/osbuilder/image-builder/../scripts:/scripts -v /build/kata-containers/tools/osbuilder/ubuntu_rootfs:/rootfs -v /build/kata-containers/tools/osbuilder:/image -v /etc/mke2fs.conf:/etc/mke2fs.conf:ro image-builder-osbuilder bash /osbuilder/image_builder.sh -o /image/kata-containers.img /rootfs
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: apply caps: operation not permitted: unknown.
time="2021-07-09T09:34:16Z" level=error msg="error waiting for container: context canceled"
make: *** [Makefile:124: /build/kata-containers/tools/osbuilder/kata-containers.img] Error 125
```

**Comment by devimc** [comment]
conclusion: we don't have enough privileges to build the image using docker in these systems (launchpad/snapcraft.io) hence we need a bare metal or VM

**Comment by Jakob-Naucke** [comment]
> conclusion: we don't have enough privileges to build the image using docker in these systems (launchpad/snapcraft.io) hence we need a bare metal or VM

@devimc Travis wouldn't happen to be better at this, would it?

**Comment by jodh-intel** [comment]
Last time I checked, you either got an LXC container or a docker env, but both are run in VMs, so I doubt it.

**Comment by devimc** [comment]
@Jakob-Naucke 

> @devimc Travis wouldn't happen to be better at this, would it?

I don't know, I use github actions for x86_64

**Comment by jodh-intel** [comment]
@devimc - I thought we could build the image using osbuilder without docker?

**Comment by devimc** [comment]
@jodh-intel we can, but some architectures need `alpine` or `ubuntu` or `fedora` and we cannot choose the distro in these build (canonical :wink: ) systems

**Comment by Jakob-Naucke** [comment]
@devimc image needs `--privileged` for `losetup`, but initrd doesn't seem to require this. Can you try this with my [snap-390-ppc-initrd branch](https://github.com/Jakob-Naucke/kata-containers/tree/snap-390-ppc-initrd)?

**Comment by devimc** [comment]
@Jakob-Naucke sorry I can't, branches are not configurable :disappointed:

**Comment by Jakob-Naucke** [comment]
okay, here we go #2219

**Comment by Jakob-Naucke** [comment]
@devimc please retry now :)

**Comment by devimc** [comment]
@Jakob-Naucke didn't work, qemu is build twice , any thoughts ?

```
Cleaning later steps and re-building qemu (properties changed)
+ yq=/build/kata-containers/stage/yq
+ export GOPATH=/build/kata-containers/stage/gopath
+ GOPATH=/build/kata-containers/stage/gopath
+ kata_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers
+ versions_file=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/versions.yaml
+ case "$(uname -m)" in
++ uname -m
++ /build/kata-containers/stage/yq r /build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/versions.yaml assets.hypervisor.qemu.version
+ branch=v5.2.0
++ /build/kata-containers/stage/yq r /build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/versions.yaml assets.hypervisor.qemu.url
+ url=https://github.com/qemu/qemu
+ commit=
++ echo v5.2.0
++ sed -e 's/.[[:digit:]]*$//' -e 's/^v//'
+ patches_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/5.2.x
+ patches_version_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/tag_patches/v5.2.0
+ qemu_dir=/build/kata-containers/stage/qemu
+ git clone --branch v5.2.0 --single-branch https://github.com/qemu/qemu /build/kata-containers/stage/qemu
fatal: destination path '/build/kata-containers/stage/qemu' already exists and is not an empty directory.
Failed to run 'override-build': Exit code was 128.
Build failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 231, in run
    self.build()
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 220, in build
    env=env)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 100, in run_build_command
    return self.backend.run(args, env=full_env, **kwargs)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/lxd.py", line 537, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lxc', 'exec', 'lp-focal-s390x', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build-request-id": "lp-64723870", "build-request-timestamp": "2021-07-13T12:41:09Z", "build_url": "https://launchpad.net/~build.snapcraft.io/+snap/029f6c9452eb983c086114e2929f7413/+build/1464290"}', '--env', 'SNAPCRAFT_BUILD_ENVIRONMENT=host', '--env', 'http_proxy=http://10.10.10.1:8222/', '--env', 'https_proxy=http://10.10.10.1:8222/', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/kata-containers && linux64 snapcraft']' returned non-zero exit status 2.
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=lxd --series=focal --arch=s390x SNAPBUILD-1464290
Scanning for processes to kill in build SNAPBUILD-1464290
```

**Comment by Jakob-Naucke** [comment]
@devimc this occurs whenever a QEMU build fails and `${kata_containers_dir}/stage/qemu` isn't removed, also on x86. It has to be removed.

**Comment by Jakob-Naucke** [comment]
> snap CI is passing in x86_64

@devimc yes, because GitHub Actions gives you a fresh env every time. I don't know exactly how one controls Snapcraft, but there is something left in the Snapcraft environment that must be removed.

**Comment by Jakob-Naucke** [comment]
see #2250

**Comment by Jakob-Naucke** [comment]
with #2250 merged -- @devimc care to retry a fourth time? 😅

**Comment by devimc** [comment]
@Jakob-Naucke thanks, but now the error is different 

```
+ '[' -z '' ']'
WARNING: Forcing LIBC=gnu because s390x has no musl Rust target
+ '[' s390x == ppc64le ']'
+ '[' s390x == s390x ']'
+ LIBC=gnu
+ echo 'WARNING: Forcing LIBC=gnu because s390x has no musl Rust target'
+ '[' gnu == musl ']'
+ rustup show
+ grep linux-gnu
/build/kata-containers/tools/osbuilder/rootfs-builder/rootfs.sh: line 546: rustup: command not found
+ bash /build/kata-containers/tools/osbuilder/rootfs-builder/../../../ci/install_rust.sh
/build/kata-containers/tools/osbuilder/rootfs-builder/../../../ci/lib.sh: line 20: CI: unbound variable
++ error_handler
++ '[' 1 -eq 0 ']'
++ '[' -n '' ']'
+ after_stopping_container
+ return 0
make: *** [Makefile:87: /build/kata-containers/tools/osbuilder/.ubuntu_rootfs.done] Error 1
Failed to run 'override-build': Exit code was 2.
Build failed
```

**Comment by Jakob-Naucke** [comment]
@devimc that is, by extension, my fault, see #2284

**Comment by Jakob-Naucke** [comment]
@devimc again :)

**Comment by devimc** [comment]
@Jakob-Naucke 

unable to re-build qemu, this is weird, isn't it?

```
Skipping pull qemu (already ran)
Cleaning later steps and re-building qemu ('override-build' property changed)
+ yq=/build/kata-containers/stage/yq
+ export GOPATH=/build/kata-containers/stage/gopath
+ GOPATH=/build/kata-containers/stage/gopath
+ export GO111MODULE=auto
+ GO111MODULE=auto
+ kata_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers
+ versions_file=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/versions.yaml
+ case "$(uname -m)" in
++ uname -m
++ /build/kata-containers/stage/yq r /build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/versions.yaml assets.hypervisor.qemu.version
+ branch=v5.2.0
++ /build/kata-containers/stage/yq r /build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/versions.yaml assets.hypervisor.qemu.url
+ url=https://github.com/qemu/qemu
+ commit=
++ echo v5.2.0
++ sed -e 's/.[[:digit:]]*$//' -e 's/^v//'
+ patches_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/5.2.x
+ patches_version_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/tag_patches/v5.2.0
+ qemu_dir=/build/kata-containers/stage/qemu
+ git clone --branch v5.2.0 --single-branch https://github.com/qemu/qemu /build/kata-containers/stage/qemu
fatal: destination path '/build/kata-containers/stage/qemu' already exists and is not an empty directory.
Failed to run 'override-build': Exit code was 128.
Build failed
````

**Comment by Jakob-Naucke** [comment]
@devimc that's definitely weird. Are you 100% sure this was latest main? The printed commands _exactly_ match e.g. https://github.com/kata-containers/kata-containers/blob/f7c6f17060d47f11530418dad53d96bf65178180/snap/snapcraft.yaml#L247-L273 but not the latest https://github.com/kata-containers/kata-containers/blob/b817340f94f050c41c743bac1e601ce38a3050b7/snap/snapcraft.yaml#L247-L275 (N.B. L. 274)

**Comment by devimc** [comment]
@Jakob-Naucke yes, it's using the latest main, but for some strange reason the first time it builds qemu the directory is removed but not the second time

**first time**

```
++ echo v5.2.0
++ sed -e 's/.[[:digit:]]*$//' -e 's/^v//'
+ patches_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/5.2.x
+ patches_version_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/tag_patches/v5.2.0
+ qemu_dir=/build/kata-containers/stage/qemu
+ rm -rf /build/kata-containers/stage/qemu
+ git clone --branch v5.2.0 --single-branch https://github.com/qemu/qemu /build/kata-containers/stage/qemu
Cloning into '/build/kata-containers/stage/qemu'...
Note: switching to '553032db17440f8de011390e5a1cfddd13751b0b'.
```

**second time**

```
+ commit=
++ echo v5.2.0
++ sed -e 's/.[[:digit:]]*$//' -e 's/^v//'
+ patches_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/5.2.x
+ patches_version_dir=/build/kata-containers/stage/gopath/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/tag_patches/v5.2.0
+ qemu_dir=/build/kata-containers/stage/qemu
+ git clone --branch v5.2.0 --single-branch https://github.com/qemu/qemu /build/kata-containers/stage/qemu
fatal: destination path '/build/kata-containers/stage/qemu' already exists and is not an empty directory.
Failed to run 'override-build': Exit code was 128.
```


full log https://paste.centos.org/view/e4ac1ed9

**Comment by Jakob-Naucke** [comment]
@devimc thanks for the log! So after some digging, this doesn't seem so weird any more.
I still don't know why snapcraft.io wants to rebuild QEMU again when that doesn't happen on my machine, but I can see that after a build, the repo is checked out to 2.2.0-alpha1, our latest release, **which doesn't have this fix**.
I wonder whether this checkout is due to https://github.com/kata-containers/kata-containers/blob/b817340f94f050c41c743bac1e601ce38a3050b7/snap/snapcraft.yaml#L24-L27

**Comment by devimc** [comment]
@Jakob-Naucke 

> I wonder whether this checkout is due to 

I don't think so

```
Pulling metadata 
+ version=9999
+ kata_url=https://github.com/kata-containers/kata-containers
/bin/bash: line 32: GITHUB_REF: unbound variable
+ grep -q -E '^refs/tags'
+ snapcraftctl set-grade stable
```

**Comment by Jakob-Naucke** [comment]
@devimc you're right. It's because of this: https://github.com/kata-containers/kata-containers/blob/b817340f94f050c41c743bac1e601ce38a3050b7/snap/snapcraft.yaml#L118 in combination with this: https://github.com/kata-containers/kata-containers/blob/b817340f94f050c41c743bac1e601ce38a3050b7/tools/osbuilder/rootfs-builder/rootfs.sh#L556-L558 Should we simply checkout to main after the agent build?

**Comment by devimc** [comment]
> Should we simply checkout to main after the agent build?

**Comment by Jakob-Naucke** [comment]
> > Should we simply checkout to main after the agent build?
> 
> no, because the release tag won't be honoured

@devimc Guest image is built with release tag agent, afterwards we checkout to main (where we were before), what's the problem?

Snaps have also stopped working in GitHub actions:
```
 + echo 'INFO: Get rust version from /home/runner/work/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/../../../versions.yaml'
++ /usr/local/bin/yq r -X - languages.rust.meta.newest-version
++ cat /home/runner/work/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/../../../versions.yaml
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
+ RUST_VERSION=
+ '[' 1 == 0 ']'
+ die 'Could not detect the required rust version for AGENT_VERSION='\''2.2.0-alpha1'\''.'
+ error 'Could not detect the required rust version for AGENT_VERSION='\''2.2.0-alpha1'\''.'
+ local 'msg=Could not detect the required rust version for AGENT_VERSION='\''2.2.0-alpha1'\''.'
+ echo 'ERROR: Could not detect the required rust version for AGENT_VERSION='\''2.2.0-alpha1'\''.'
ERROR: Could not detect the required rust version for AGENT_VERSION='2.2.0-alpha1'.
+ exit 1
make: *** [Makefile:87: /home/runner/work/kata-containers/kata-containers/tools/osbuilder/.alpine_rootfs.done] Error 1
```

**Comment by fgiudici** [comment]
I think the snaps issue here is due to having yq v4 installed. yq v4 changed syntax in an incompatible way...
opened a new issue: https://github.com/kata-containers/kata-containers/issues/2297
I'm preparing a PR for that.

**Comment by Jakob-Naucke** [comment]
So I'm not entirely sure what Snapcraft does, and maybe `snapcraft.io`'s behaviour is also different from `/usr/bin/snapcraft`'s, so I can't know for sure.
But either it checks out everything to a version except `snap/snapcraft.yaml`, or it just builds from `main` (which is what it does on my machine anyways).
In the former case, I think this line https://github.com/kata-containers/kata-containers/blob/3160f0102dbc6eb7d03480e11a1f2dc97b402d5e/snap/snapcraft.yaml#L118 which causes the agent scripts to check out the entire repository to the content of `VERSION`, should go because it would be unnecessary.
In the latter case, I think that line should go because it would be inconsistent to build everything but the agent from `main`, and build the agent from `VERSION`.
Either way, this line causes the checkout to a buggy `snapcraft.yaml`.
WDYT @devimc?

**Comment by jodh-intel** [comment]
I'm not entirely sure how the YAML handles variables in different parts, but if they are exported, couldn't we just do:

```bash
export AGENT_VERSION="$version"
```

Where `version` is set https://github.com/kata-containers/kata-containers/blob/main/snap/snapcraft.yaml#L25 @devimc?

**Comment by devimc** [comment]
@jodh-intel @Jakob-Naucke  yes, we should get rid of `export AGENT_VERSION=$(cat ${kata_dir}/VERSION)`

**Comment by Jakob-Naucke** [comment]
see #2314

**Comment by devimc** [comment]
@Jakob-Naucke the snap for s390x and ppc has been released under the edge channel (https://snapcraft.io/kata-containers), version ID is 9999 since it was built using main, should I move it to stable ?

**Comment by Jakob-Naucke** [comment]
Hmm. The distributed config has this:
```
[hypervisor.qemu]
path = "/snap/kata-containers/current/usr/bin/qemu-system-s390x"
kernel = "/snap/kata-containers/current/usr/share/kata-containers/vmlinux.container"
machine_type = "s390-ccw-virtio"
```

without an initrd configured, so you can't start a container OOTB (even though the initrd is there). Let me TAL.

**Comment by Jakob-Naucke** [comment]
see #2331

**Comment by Jakob-Naucke** [comment]
@devimc one more please :)

**Comment by devimc** [comment]
@Jakob-Naucke done, a new version has been released

**Comment by Jakob-Naucke** [comment]
```
$ uname -m
s390x
$ snap install --edge kata-containers --classic
kata-containers (edge) 9999 from Kata Containers (katacontainers✓) installed
$ ctr run --runtime io.containerd.kata.v2 -t --rm quay.io/prometheus/busybox:latest foo echo finally
finally
```

@devimc awesome and thank you for your help! Can you move to stable?

**Comment by Jakob-Naucke** [comment]
@Amulyam24 want to try on ppc64le?
@devimc what about ARM? Thought it was fixed now

**Comment by devimc** [comment]
@Jakob-Naucke  sure I can move them to stable, arm is still broken

**Comment by Amulyam24** [comment]
Thanks @Jakob-Naucke and @devimc , the install and run works fine on ppc64le :)

**Comment by jongwu** [comment]
Hi @devimc -, snap on arm works now. So can you help push arm snap build to stable channel?

**Comment by simos** [comment]
Near the green `Install` button you can find all the available versions per architecture, https://snapcraft.io/kata-containers

### `amd64`

Channel | Version | Last update
-- | -- | -- 
latest/stable | 2.4.2 | 8 June 2022 
latest/candidate | 2.1.0 | 14 May 2021 
latest/beta | 2.0.1 | 4 December 2020   
latest/edge | 9999 | 25 May 2022 

1. The latest stable version is at `2.4.2` while the _2.x line_ is currently at `2.5.2`.
2. The `candidate` and `beta` packages are too old. A package would be a `candidate` for a few days before it gets upgraded to `stable`. Similarly with `beta`. 
3. The `edge` package has stopped updating. 
4. Ideally, there should be `2.4/stable`, `2.5/stable`, `3.0/stable` channels. Similarly to what you get with the `lxd` snap package. 
5. There are similar issues with the other architectures.

**Comment by jodh-intel** [comment]
Related: #5793.
